### ISSUE TITLE
Printing in Firefox upsets formatting

### ISSUE THREAD

**Issue by dnschnur** [flot/flot#104]
_Original author: analyt...@concisewebdesign.co.uk (February 01, 2008 17:28:02)_

It would be really nice if the graphs maintained their appearance when printed

_Original issue: http://code.google.com/p/flot/issues/detail?id=25_

**Comment by realgsg** [comment]
hi sir! the lines of chart do not show up in print preview, how to sole it please?

1, chart fills with data:
![image](https://user-images.githubusercontent.com/20250599/45825303-886b3600-bd24-11e8-92b6-a098f8763b3f.png)


2, the axes are present, but the data and the grid lines are missing.
![image](https://user-images.githubusercontent.com/20250599/45825173-3a563280-bd24-11e8-8cfc-932ed2140854.png)
