### ISSUE TITLE
Null items at the end of a data collection are not rendered

### ISSUE THREAD

**Issue by munr** [flot/flot#1095]
In Flot 0.8.1, null items at the end of a data collection are ignored and not rendered as gaps in the chart.

Example code:

```
var d1 = [];    

// Add some random numbers
for (var i = 0; i <= 3; i += 1)
    d1.push([i, parseInt(Math.random() * 30)]);

// Add some null values
for (var i = 4; i <= 10; i += 1)
    d1.push([i, null]);

// Render the chart
$.plot($("#placeholder"), [d1], {
    series: {
        bars: {
            show: true
        }
    }
});
```

This renders the following type of chart:

![Image](http://i.imgur.com/0HNtlZV.png)

Note how the null items at the end of the collection were not rendered.

Using Flot 0.7, the same data code renders the following:

![Image](http://i.imgur.com/ojYVjE0.png)

This is the desired (and correct) behavior, where the null items at the end of the collection are rendered as gaps.

It looks like something changed between 0.7 and 0.8.1 which introduced this bug.

**Comment by harrydet** [comment]
Not sure if this project is still maintained, but I'm having the same issue. Nulls are not rendered if they are at the beginning or end of the data array. I'm using version 0.8.3.

**Comment by aishwarya-bote** [comment]
I'm using version 0.8.1.
With the fix given above,nulls are rendered if they are in the middle of the data but not if they are in the beginning or in the end.It just skips those points on the axis.
