### ISSUE TITLE
Pie Chart - Undesirable inner white circle

### ISSUE THREAD

**Issue by duboisp** [flot/flot#1128]
Hi,

When a simple pie chart co-exist with a donnut pie chart and both get executed in that order, that create an undesirable white circle on all the previous pie chart that have a lower inner radius.

![piechartinnerradiusissue](https://f.cloud.github.com/assets/1676030/1085442/b7014bea-15d0-11e3-8f9b-9022fe4232b3.png)

**Working Demo:** http://jsfiddle.net/LvQ9e/5/
**jQuery Version:** 1.8.3
**Browser:** Firefox 22.0, IE10, Chrome 29.0.1547.62m
**Other libraries:** Pie Flot Plugin (jquery.flot.pie.js)
**How to reproduce:** If the last generated chart have an inner radius greater than the previous one, all the other pie chart get an inner white circle that match the `innerradius` property of the last generated pie chart. This also influence the hovering effect of the previous pie chart. The hovering effect are only visible from the white circle to the external side of the pie chart.

**Here some scenarios that was tested:**

If we have the following kind of chart:
- [standard]: pie chart that have an inner radius set to 0
- [donut A]: pie chart that have an inner radius set to 0.45
- [donut B]: pie chart that have an inner radius set to 0.70
- [bar]: bar chart _or any other basic chart that do not require the flot pie chart plugin_

The result, classified by execution order, will be:
- [standard] + [donut A] = white circle bug on [standard]
- [standard] + [standard] + [donut A] = white circle bug on both [standard]
- [donut A] + [standard] + [donut B] = white circle bug on [standard] and [donut A]
- [donut A] + [standard] + [donut B] + [bar] = white circle bug on [standard] and [donut A]
- [donut A] + [standard] + [donut B] + [bar] + [standard] = No bug
- [donut A] + [standard] + [donut B] + [bar] + [standard] + [donut A] = white circle bug on both [standard]
- [donut A] + [donut B] = white circle bug on [donut A]
- [donut B] + [donut A] = No bug

**Other Information**
This issue was also discussed here: https://github.com/wet-boew/wet-boew/pull/2840#issuecomment-23688240

---

Cheers

:smiley:

**Comment by Slman42** [comment]
Help me to Reduce the Inner Radius in Multi-Level-PieChart? please

**Comment by SoumyaCjee** [comment]
![flot-bug](https://user-images.githubusercontent.com/37110852/37092261-29120550-2231-11e8-8800-fa0d0e331688.PNG)
![flot](https://user-images.githubusercontent.com/37110852/37092316-6f4b9a86-2231-11e8-9e86-565bfd46aa52.PNG)
 there is small cricle issue.can someone say what to do to remove that circle?.it is not coming every time,it is coming for a specific value.i can not resolve it.please help me out,it's urgent..
Thank you in advance :)
