### ISSUE TITLE
Gap on full-width chart when showing x axis

### ISSUE THREAD

**Issue by Shpigford** [flot/flot#1212]
I have a chart that I want to span 100% within its parent container. It works like I want as long as I have the xaxis show option turned off.

But once I turn it on, it adds a gap on the left (as you can see from the attached image). The right is fine.

![side_gap](https://f.cloud.github.com/assets/35243/1782359/587612a8-68ab-11e3-9cd8-c002d7f252bd.png)

Any ideas? Here are my grid and xaxis settings:

```
grid: {
  borderColor: 'transparent',
  hoverable: false,
  backgroundColor: 'transparent',
  minBorderMargin: 0,
  borderWidth: 0,
  margin: {
    top: 10,
    right: 0,
    bottom: 0,
    left: 0
  }
},
xaxis: {
  show: true,
  mode: "time",
  timezone: 'browser',
  timeformat: "%b",
  minTickSize: [1, "month"],
  reserveSpace: false,
  font: {
    size: 11,
  }
}
```

**Comment by plumbblake** [comment]
Same problem as Mushr0000m for me. When I pass in a custom array for xaxis ticks I get a gap on the right. When I don't provide a custom array the graph fills up the space correctly.
