### ISSUE TITLE
add bower

### ISSUE THREAD

**Issue by gbelmm** [flot/flot#1367]
please add bower

**Comment by jeremypepper** [comment]
Does `bower install flot --save` not work for you?

**Comment by camilonova** [comment]
I can confirm it works, this issue can be closed.

**Comment by sandermarechal** [comment]
This does not work. The component.json user "Flot" with a capital F as the name. Bower refuses to parse this:

bower flot#0.8.3 EINVALID Failed to read /tmp/sander/bower/flot-17967-iay3ei/component.json

See also #1410
