### ISSUE TITLE
May you please update the NPM package?

### ISSUE THREAD

**Issue by ibc** [flot/flot#1381]
It's outdated since 2 years:

https://www.npmjs.org/package/flot

**Comment by theofidry** [comment]
+1

**Comment by andig** [comment]
Hint: If using Travis-CI you can automate the process of pushing to npm on each commit.

**Comment by mark-rushakoff** [comment]
Flot is evidently abandoned so I wouldn't hold my breath on an updated NPM package. As a workaround you can use `npm install --save git+https://github.com/flot/flot.git#v0.8.3` to install the package as of the v0.8.3 tag.

**Comment by jamie-pate** [comment]
Note also, that the package name is wrong in package.json. This will cause issues with npm prune etc.

it should be

```json
"dependencies": {
    "Flot": "git+https://github.com/flot/flot.git#v0.8.3",
    ...
```

PS: please switch the package.json to match the npm module capitalization if you ever do this, or npm will explode (No really, like, KABOOM)

**Comment by Beakerboy** [comment]
#1609 updates the 0.8 NPM branch
