### ISSUE TITLE
Is flot dead?

### ISSUE THREAD

**Issue by andig** [flot/flot#1390]
The last blog post and commit are from april and may respectively. Issues and suggested PRs don't seem to get too much attention lately. Much-needed functionality like e.g. proper touch support are not or only halfheartedly available.

I would be interested in what the near future will bring for flot.

**Comment by markrcote** [comment]
@qking Hi, I've talked to the other maintainers and what you're proposing sounds pretty reasonable. Could you email me at mcote@mozilla.com to discuss further?

**Comment by qking** [comment]
Sorry for the long long silence. I was overly optimistic about the time my engineer can put into Flot at this point. He has his hands full with all the elements of our new acquisition interface that will embed the flot chart.  So for now, he is using Flot-0.83 and hasn't invested any time to improve it. We are even considering forking a reduced feature set from flot to allow us to optimise further. We only need to show time series data with constant period so a lot of the features in flot are not necessary for us. The approach we will take should clarify in the second half of the year and I'll write again then.

**Comment by mukulchakane** [comment]
Yes it's dead now, and no longer maintained by flot team and no recent pull requests seen
