### ISSUE TITLE
please support bower

### ISSUE THREAD

**Issue by sargin48** [flot/flot#1410]
please support bower

users cant install with
cmd ->
bower install jquery.flot

**Comment by jlbooker** [comment]
Try `bower install flot --save`

**Comment by camilonova** [comment]
I can confirm it works, this issue can be closed.

**Comment by sandermarechal** [comment]
This does not work. The component.json user "Flot" with a capital F as the name. Bower refuses to parse this:

bower flot#0.8.3                     EINVALID Failed to read /tmp/sander/bower/flot-17967-iay3ei/component.json

**Comment by jlbooker** [comment]
@sandermarechal the previous command works for me: `bower install flot --save`

My bower.json dependency section looks like:
```
"dependencies": {
    "typeahead.js": "0.11.*",
    "flot": "~0.8.3"
  }
```

You should be using all lower-case letters in the name `flot`.

**Comment by sandermarechal** [comment]
@jlbooker What version of Bower are you using? I have a lowercase "flot" specified in my own bower.json. The problem is the component.json in flot's repository that specifies it using a captial F.

**Comment by jlbooker** [comment]
`bower --version` says `1.4.1`, which seems to be the current release.

**Comment by sandermarechal** [comment]
Not sure what was causing it, but it seems to work now. You can close this.
