### ISSUE TITLE
CTRL + P not working

### ISSUE THREAD

**Issue by mtsys** [flot/flot#1439]
I'm using flot in the preview in html is ok. But by doing CTRL + P, the preview does not show the report. How do you see the flot?

HTML
http://i.imgur.com/ZzWeORX.png

Preview
http://i.imgur.com/om05cEh.png

I test to url http://www.flotcharts.org/flot/examples/basic-usage/index.html and not working.

**Comment by maxsteenbergen** [comment]
Flot renders a ````<canvas>```` element, which cannot be printed out of the box. You'll have to rasterise the chart to  e.g. PNG or JPG before printing. See http://stackoverflow.com/questions/923885/capture-html-canvas-as-gif-jpg-png-pdf

**Comment by mtsys** [comment]
I have 2 graphics. But it does not generate the id, you know how I can add the id to get the asism data:

var canvas = document.getElementById ("mycanvas");

**Comment by mtsys** [comment]
tks
