### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by gorkem-cetin** [flot/flot#1468]
I see that latest github commit was done over a year ago. Some of the questions are not answered. Many pull requests are there awaiting to be merged. 

I might be overlooking something but wanted to ask to project maintainers whether this project is still alive (maintained) or not?

**Comment by dnschnur** [comment]
I haven't been able to maintain it since a couple of years ago. We had someone volunteer as maintainer a few months ago, but I don't think anything came of that.

**Comment by gorkem-cetin** [comment]
Since Flot is an open source project, in order to be open to the public that you are not maintaining it anymore, there better be a way to make everyone know that in your readme.md, so people will adjust their expectancy about their future use. If there are bugs in an open source project, developers would like to know that those are not fixed by the main maintainer. 

What do you think?

**Comment by kokarn** [comment]
Maybe transfer ownership to somebody? @torkelo is using it a lot in Grafana, maybe they'd like to support it?

**Comment by sandebert** [comment]
I agree with @gorkem-cetin and @kokarn , it would be very good for flot to be more clear with the current lack of maintainers, and it would be extremely beneficial to hand it over to somebody that can help it evolve further.

**Comment by GermanBluefox** [comment]
Hello,
We are using flot in ioBroker too and it is important to know about the
future development and maintenance.
It would be good if flot will go forward. And grafana teem is not bad
solution.

Greetings
13 Окт 2015 г. 11:10 пользователь "Fredrik Sandebert" <
notifications@github.com> написал:
