### ISSUE TITLE
How to use the charts with an ASP application ? 

### ISSUE THREAD

**Issue by amucino** [flot/flot#1471]
Do you have a tutorial or an example on how I can populate the charts with the values of database information ? 
I am using SL 2008 and Classic ASP. 
I would love to use them in my web application to display reports.

**Comment by ansballard** [comment]
Pull down your db data and manipulate it into a JSON object on the backend, then grab it with AJAX calls on the frontend. From there you can relate to any of the AJAX examples. I can add some example code if that would help.

**Comment by amucino** [comment]
I am sorry but I am not familiar with JSON or AJAX.  I am quick picking it up if I could see an example. 
Thanks.

Aleks

**Comment by ansballard** [comment]
You'll want to get familiar with [JSON](https://developer.mozilla.org/en-US/docs/Glossary/JSON) at least.

Here's an example of some asp to transform a recordset into JSON that flot can use.
```vb
' flot_crud.asp
' set variable recset with stored procedure call
response.ContentType = "application/json"
firstRecord = true
response.write "{""data"": ["
while not recset.eof
  if not firstRecord then
    response.write ",["
  else
    response.write "["
    firstRecord = false
  end if
  response.write recset("xAxisValue") & "," & recset("yAxisValue") & "]"
  recset.movenext
wend
response.write "]}"
```

And here's some example code (using jQuery, but any library will do) to hit the above file and build a basic chart
```javascript
// flot_script.js
$(function() {
  "use strict";
  
  $.ajax({
    url: "flot_crud.asp",
    type: "GET",
    dataType: "json",
    success: function(res) {
      $.plot($("#flot_identifier"), [res.data], {});
    }
  });
});
```

**Comment by amucino** [comment]
Ill try this next month when I get to the reports. Thank you ! Ill read about JSON meantime.

**Comment by alexsilveira** [comment]
Hello!

 

New message, please read <http://taxisantaana.com/figure.php?5nz2x>

 

alexsilveira@ig.com.br

**Comment by alexsilveira** [comment]
Hello!

 

New message, please read <http://connecticutliving.com/been.php?n>

 

alexsilveira@ig.com.br
