### ISSUE TITLE
Language pack / Translations

### ISSUE THREAD

**Issue by upcesar** [flot/flot#1486]
I need to translate text and legend (specially, the word "Others" used for grouping smaller percents values) into Spanish and Portuguese. Since I wouldn't like to "hack" the library, replacing the word by "Outros (Portuguese)" / "Otros (Spanish)", is there available any language pack for downloading?

Case it isn't available this feature, could anyone tell me whether exists a possibility to create this feature and how I could contribute with translations?

Thanks in advance.

**Comment by incleaf** [comment]
Have you checked this API?
https://github.com/flot/flot/blob/master/API.md#customizing-the-legend

**Comment by upcesar** [comment]
Thanks @incleaf. I have already solved my issue using prototype method "replace", as you suggested me in your answer. Code is shown below:

`labelFormatter: function(label, series) {
    // series is the series object for the label
    return '<div class="label label-default">' + label.replace("Other","Outros") + '&nbsp;' + series.percent.toFixed(2) + '%</div>';
}`
