### ISSUE TITLE
Negative area filled wrongly

### ISSUE THREAD

**Issue by maeishoj** [flot/flot#1507]
Hi everyone.

How can i get my chart area to render properly when having negative values? here is how it looks right now:

![screen shot 2016-07-22 at 15 10 54](https://cloud.githubusercontent.com/assets/1631903/17058200/49ad471a-501f-11e6-823e-672609494c58.png)

**Comment by Herohtar** [comment]
What's wrong with how that's filled?

**Comment by maeishoj** [comment]
That it's inverted. Since the temperature is negative, the area that should be filled is the one underneath from -21 degrees (lowest temperature) to -7 (highest temperature), not from 0 downwards.

**Comment by BugHunter2k** [comment]
IMHO the filling behavior in your case is absolutely correct. Filling in graphs should be starting at 0.
Therefore negative areas should be filled downwards, positive upwards.

**Comment by andig** [comment]
I don't fully remember but there was something about adding another value to your tuples that indicates from where on the fill should happen.

**Comment by jarekdobrzanski** [comment]
from the docs:

> Lines and points take two coordinates. For filled lines and bars, you can specify a third coordinate which is the bottom of the filled area/bar (defaults to 0)

I think we can close this one
