### ISSUE TITLE
Save flot as image on iOS / touch.

### ISSUE THREAD

**Issue by MatBenfield** [flot/flot#1519]
I'm happy all my charts display ok on iOS devices. I have a plugin, however, to save flot charts as images^ but this doesn't work on iOS does anyone know of a plugin or some JavaScript to help?

 At the moment I get empty touch element - this might be a more generic js issue.

^I generate charts with PHP and want to save them as images to include in a blog post and social media share. I can do this in any browser on Mac / Windows, but I am now running an iOS only set up.

Many thanks

![img_0778](https://cloud.githubusercontent.com/assets/1188107/18573335/4eda0e28-7bba-11e6-8b64-ca0e89115adc.PNG)

**Comment by andig** [comment]
I don't know about iOS but I'm using this approach here https://github.com/volkszaehler/volkszaehler.org/blob/master/htdocs/frontend/javascripts/wui.js#L91 to save on Safari on Mac. See index.html for the included js libraries.
