### ISSUE TITLE
www.flotcharts.org is down

### ISSUE THREAD

**Issue by janesma** [flot/flot#1527]
http://www.flotcharts.org/

404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

**Comment by jeffconklin** [comment]
Was about to mention the same thing.

**Comment by nicholeapo** [comment]
Any news?

**Comment by TrilceAC** [comment]
Suffering the same issue too. According to https://twitter.com/githubstatus there was a major outage of service yesterday, but theoretically the service is operating normally. Yesterday, when the service was restored, I could briefly load the main page without images once, but I couldn't really access to any valuable piece of information.

**Comment by dnschnur** [comment]
Github deprecated git:// submodule references; fixed by switching to https://.
