### ISSUE TITLE
Cannot read property 'save' of null

### ISSUE THREAD

**Issue by adripanico** [flot/flot#1529]
After updating jQuery from 2.2.1 to 3.1.1, the browser console is showing an error when the graph has no values:

```
jquery.flot.min.js:8 Uncaught TypeError: Cannot read property 'save' of null(…)
```

The exact method that raises this error:

```
function drawOverlay() {
  redrawTimeout = null;

  // draw highlights
  octx.save();
  overlay.clear();
  octx.translate(plotOffset.left, plotOffset.top);

  var i, hi;
  for (i = 0; i < highlights.length; ++i) {
    hi = highlights[i];

    if (hi.series.bars.show)
      drawBarHighlight(hi.series, hi.point);
    else
      drawPointHighlight(hi.series, hi.point);
  }
  octx.restore();

  executeHooks(hooks.drawOverlay, [octx]);
}
```

**Comment by paulsc** [comment]
I have the same issue. Is there a fix ?

**Comment by adripanico** [comment]
Stop using the library. It is not being mantained. You can try Chart.js for instance.

Good luck.

**Comment by mihaisdm** [comment]
Why is issue closed, if no fix?
Did you found workarounds?

**Comment by adripanico** [comment]
More than two years after the original comment, I think nobody is taking a look at this.

**Comment by Beakerboy** [comment]
The Flot library has had a slew of new development recently. What version of Flot are you using?
