### ISSUE TITLE
flot chart , after webpack not working

### ISSUE THREAD

**Issue by Meesam** [flot/flot#1539]
browser shows :-   TypeError: $.plot is not a function

**Comment by NiB18** [comment]
I had the same problem, it's not a library issue but problem with the way you import it to your code. You have to require it so library code is executed - added to jQuery plugin factory.

**Comment by RafaelLiendo** [comment]
just to compliment @patrikniebur answer
instead of:
```typescript
import 'flot/jquery.flot'
import 'flot/jquery.flot.time'
```
use:
```typescript
require('flot/jquery.flot');
require('flot/jquery.flot.time');
```
and if typescript says 
```
Cannot find name 'require
```
try this:
https://stackoverflow.com/questions/43104114/cannot-find-name-require-after-upgrading-to-angular4#answer-43129815
