### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by tomvo** [flot/flot#1549]
The latest version on NPM is 0.8.0-alpha, would be great if that could get an update

**Comment by matt-senseye** [comment]
I agree - this caught me out too. As a temporary solution, you can `npm install flot/flot#0.8.3` or `yarn add flot/flot#0.8.3` which adds the dependency as:

`"Flot": "flot/flot#0.8.3"`

**Comment by Beakerboy** [comment]
#1609 resolves this.
