### ISSUE TITLE
Plotclick event is being fired twice when replotting

### ISSUE THREAD

**Issue by dnschnur** [flot/flot#156]
_Original author: meyuc...@gmail.com (November 09, 2008 13:42:32)_

<b>What steps will reproduce the problem?</b>
1. $.plot($(&quot;#chart&quot;), data, options);
2. $(&quot;#chart&quot;).bind(&quot;plotclick&quot;, function(event, pos, item) { alert(1); });
3. $(&quot;#chart&quot;).empty();
4. $.plot($(&quot;#chart&quot;), data, options);
5. $(&quot;#chart&quot;).bind(&quot;plotclick&quot;, function(event, pos, item) { alert(1); });

<b>What is the expected output? What do you see instead?</b>
Plotclick is being fired twice when clicking the plot.

<b>What version of the product are you using? On what operating system?</b>
0.5, IE6.

<b>Please provide any additional information below.</b>
I guess events should be cleared when plotting on target.

_Original issue: http://code.google.com/p/flot/issues/detail?id=77_

**Comment by santosh-k1** [comment]
@dnschnur Thanks fixed the issue by using your concepts 

 $("#plot").unbind("plotclick").bind("plotclick", function (event, pos, item) {
//events 
}
