### ISSUE TITLE
.bower.json Unexpected token }

### ISSUE THREAD

**Issue by simplenotezy** [flot/flot#1571]
bower EMALFORMED    Failed to read /Users/username/Projects/myproject/bower_components/Flot/.bower.json

Additional error details:
Unexpected token } in JSON at position 415
error Command failed with exit code 1.

The .bower.json has an extra bracket at the end:

![image](https://user-images.githubusercontent.com/3786627/35350966-ce1d4c0c-013f-11e8-8931-32573bb257b8.png)

**Comment by jarekdobrzanski** [comment]
After flot update to 2.1.6 everything seems fine. Tested by setting up clean project and:

```
npm install -g bower
bower init
bower install flot
```

And then checking the problem file:
```

cat bower_components/flot/.bower.json
{
  "name": "flot",
  "homepage": "https://github.com/flot/flot",
  "version": "2.1.6",
  "_release": "2.1.6",
  "_resolution": {
    "type": "version",
    "tag": "v2.1.6",
    "commit": "ab4d64a57eb78e12e3d2935cc82529d5b89eaeec"
  },
  "_source": "https://github.com/flot/flot.git",
  "_target": "^2.1.6",
  "_originalSource": "flot",
  "_direct": true
}
```

I think this one can be closed
