### ISSUE TITLE
How can I find the intermediate value of lines at any point in javascript?

### ISSUE THREAD

**Issue by HopfenArtur** [flot/flot#1576]
Good afternoon. suppose I have a graph "x" horizontally this time:
function newDateHour1(){
var now = new Date();
var day = now.getDate();
var month = now.getMonth();
var year = now.getFullYear();
var time = new Date(year, month, day, 7, 00, 0, 0).getTime();
return time;
};

function newDateHour2(){
var now = new Date();
var day = now.getDate();
var month = now.getMonth();
var year = now.getFullYear();
var time = new Date(year, month, day, 19, 0, 0, 0).getTime();
return time;
};

that is, the beginning of newDateHour1 = 1520913600000;
end newDateHour2 = 1520956800000;

there is an "y" start for example: 0, end 100

Draw a straight line [x, y] = the beginning [1520913600000, 0] the end [1520956800000, 100]

Now the question is how to find the intermediate value of the lines at some point in javascript? for example at the current time point:
var new = new Date().getTime();

new = 1520922847845;
![3328247_45045d60b2ee999b64d245c6c0a09e2b_800](https://user-images.githubusercontent.com/35683138/37327213-6d61e01c-26a6-11e8-8514-171ad14dc999.jpg)

**Comment by jarekdobrzanski** [comment]
This is unrelated to flot itself and should be closed. 

You need to build a linear equation from two (x,y) points provided, and then you'll be able to get y for any x. Please refer to wikipedia, khan academy or similar source on linear equations.

**Comment by Beakerboy** [comment]
Y=m*x+b
m=rise/run
rise=y2-y1
run=x2-x1
Therefore b = y2 -(y2-y1) * x2 / (x2-x1)
And then
Ynew = (y2-y1) / (x2-x1) * Xnew + y2 -(y2-y1) * x2 / (x2-x1)
