### ISSUE TITLE
How to render data as zero in empty dates in flot plugin?

### ISSUE THREAD

**Issue by Costegillio** [flot/flot#1578]
I'm using flot with its time plugin to visualize some kind of user activities per day and i have data which looks like: [[date, value], [date, value]]

Dates in UTC so everything works fine but if where are no data between two dates flot doesn't recognize that data as zero and renders straight line.

For example i have data [[1 feb, 3], [3 feb, 3]] and it's renders like:
3  -------------------------
2  
1         
0          
   1 feb | 2 feb | 3 feb

And i want result like:
3....\\............../
2......\\.........../
1.......\\......../
0.........\ _ /
   1 feb | 2 feb | 3 feb

**Comment by Beakerboy** [comment]
it seems to me that FLOT is rendering what you gave it correctly. Before passing the data to flot, you'll want to pass it to a custom function to add the missing points. the way I would do it is to make sure the data is sorted, and use a for loop. if the current value is greater than one day from the previous data point, add the appropriate number of zero points. Or, you can make use of the "straight line" and, if there are more than two days between point, just add one after the previous point, and one for the day before the current point.

**Comment by jarekdobrzanski** [comment]
Flot (and any other charting library) simply connects any supplied x,y points so if you need to sort of "break the line" you need to explicitly supply 'null' value for the given date. So 

>  [[1 feb, 3],[2 feb, null],[3 feb, 3]]

This one can be closed as non issue
