### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by klimanek** [flot/flot#1584]
Is this project dead? Have not seen any commit for over 4 years now. :/

**Comment by dennis-fedco** [comment]
sadly it looks dead.  I do wonder what happened.  Flotchart website is still operational, someone's still paying for webhosting fees.

**Comment by qking** [comment]
We're still actively using FLOT for a [data viewer](https://service-powerspy.web.cern.ch/) application and have no issues with it, but we only use a relatively small subset of its features and can't commit the effort needed to support the full product. When the version of jQuery that it plugs into becomes obsolete, then we'll have to either move to a new charting library, or take it in house and start supporting at least a subset of FLOT features. Perhaps we'll call it FLOTLITE or FLITE or something like that. 

When we last checked the alternatives, nothing came close enough to FLOT in performance. This was the main reason we used FLOT when started our data viewer project in 2015, even though it was already essentially frozen.

**Comment by ohartl** [comment]
Using flot does not make sense anymore. We were hoping for years, but the project maintainers just left and do not even seem interested in finding a new maintainer. It's sad but true.

Now we have to migrate to another library, just because our other dependencies will not work together with flot anymore :/

**Comment by qking** [comment]
@ohartl, please let us know what you choose as an alternative to flot and why. I think many flot users will be interested. There is no shortage of options according to the [Wikipedia page](https://en.wikipedia.org/wiki/Comparison_of_JavaScript_charting_libraries). Back in 2015, we compared flot with D3 and Highcharts in detail. They both made beautiful charts, but with a lot of animation options that add nothing for our dataviewer application, and they were much slower than flot.

I've found some recent comparisons on [sitepoint](https://www.sitepoint.com/15-best-javascript-charting-libraries/) and [Hackernoon](https://hackernoon.com/9-best-javascript-charting-libraries-46e7f4dc34e6). It's not clear from these how well the different libraries will handle very large datasets (>20 MSamples). I think most were not created with this priority, especially those that depend on SVG. Flot uses CANVAS and at least at the time we checked, this seemed to be linked to the improved performance of Flot over Highcharts. I expect everything has become faster, so please let us know if you find a library that is well adapted to big datasets.

**Comment by bdiamand** [comment]
http://dygraphs.com/ ?

**Comment by jarekdobrzanski** [comment]
I'm really interested in keeping flot alive. Been using it in my product for a while now, and its performance with the large data sets is great. Would be great to hear anything from maintainers on their plans ect. I'd be happy to take part in the effort to bump it to jquery 3 and then maybe even remove jquery dependency

**Comment by andrewdove1** [comment]
There will be news on this shortly. We are working through the issues. Flot is NOT dead.

**Comment by djh42** [comment]
I hope there is good news. One aspect that I hope will be considered is a forum or mailing list that does not require a google account.

**Comment by Beakerboy** [comment]
I’ve just been added to the FLOT project group here on GitHub. Anyone interested in taking on a development role should chime in.

**Comment by GermanBluefox** [comment]
> I’ve just been added to the FLOT project group here on GitHub. Anyone interested in taking on a development role should chime in.

I am using flot in ioBroker project and I am interested on keep it rolling... Please add me to the group

**Comment by jarekdobrzanski** [comment]
As I said I'm happy to contribute but it would be great to have some clarity regarding the project. I can see lots of great work [here](https://github.com/ni-kismet/engineering-flot) and was hoping for an update from maintainers of both forks on their plans and the way forward.

**Comment by Beakerboy** [comment]
The former maintainers are no longer managing the project. Currently myself and one other person have been granted maintenace roles over this repository. I have not heard from this other individual. What I would like to do is take the existing code, add some unit tests, make sure it passes a lint test, and has good code coverage. Then new features and bug fixes. There is an existing 0.9.0 branch that Spears to already pass Lint.

**Comment by Beakerboy** [comment]
Project is once again active.
