### ISSUE TITLE
jQuery Flot Chart. How to Deal With jQuery AJAX Scope: Got `$.plot is not a function` On Local Computer

### ISSUE THREAD

**Issue by handhikadj** [flot/flot#1592]
Anyway, this is the reproduction: https://codepen.io/dhika345/pen/OrPQxM

As you can see, it got ` i.css(...) is undefined` on the console. However, when I invoke it in the window, it's working

And you also can answer this issue on: https://stackoverflow.com/questions/53721391/jquery-flot-chart-how-to-deal-with-jquery-ajax-scope-got-plot-is-not-a-func

**Comment by handhikadj** [comment]
SOLVED by adding
```javascript
async: false
```
on the AJAX jquery

Thank you

**Comment by jarekdobrzanski** [comment]
The reproduction doesn't produce any result either in console or screen. I find it hard to understand the nature of the issue based on this description. If you think this is a flot issue, can you try to isolate the problem more in your example?

**Comment by handhikadj** [comment]
Google Chrome v72xxx:

![image](https://user-images.githubusercontent.com/22522638/52455982-70863880-2b85-11e9-92cf-6c06ca2687ca.png)

Mozilla Firefox Quantum v66:

![image](https://user-images.githubusercontent.com/22522638/52456031-9f9caa00-2b85-11e9-95ad-e256e03e5c09.png)

**Comment by jarekdobrzanski** [comment]
There's no way this example could work. pie-chart2 div is not even there. I've added it and set some default placeholder widths and heights and getting no errors:

![chart](https://user-images.githubusercontent.com/32457652/52851684-a5a70380-310e-11e9-8324-d3d7e26fddd5.png)

I think we can close this one as not flot related

**Comment by handhikadj** [comment]
excuse me for my typo. this is worked now
