### ISSUE TITLE
Tests fail on linux/chrome

### ISSUE THREAD

**Issue by jarekdobrzanski** [flot/flot#1600]
Firefox 64.0.0 (Ubuntu 0.0.0): Executed 308 of 314 (skipped 6) SUCCESS (3.362 secs / 3.214 secs)
Chrome 65.0.3325 (Linux 0.0.0): Executed 308 of 314 (1 FAILED) (skipped 6) (1.702 secs / 1.587 secs)
TOTAL: 1 FAILED, 615 SUCCESS

1) centers the labels of y axes vertically
     flot axis labels plugin
     Expected 2.03125 to be less than 2.
    at UserContext.<anonymous> (tests/jquery.flot.axislabels.Test.js:87:35)

npm ERR! Test failed.  See above for more details.

**Comment by andrewdove1** [comment]
TravisCI uses linux and the tests pass there. So is this just a case of not using the latest versions of browsers? I know Chrome is up to v72.

**Comment by jarekdobrzanski** [comment]
I've updated now from Chrome 65 to 72 and it's the same. I'll investigate it further.

**Comment by jarekdobrzanski** [comment]
seems like some weird karma issue. the test fails only when run by karma runner. I think we can close this one as not flot related
