### ISSUE TITLE
[URGENT] Please add older versions to npm registry

### ISSUE THREAD

**Issue by trickeyone** [flot/flot#1609]
Since this project was added to the npm registry 9 days ago, any builds that are using older versions (i.e. 0.8.x) are now failing because the npm registry only has 2.x versions.

**Comment by mure** [comment]
Hi trickeyone - as far as I can tell, the npm registry for flot previously only had a 0.8.0-alpha version and was never updated. I suppose we could add old versions to the registry, but I am a little confused on how your builds were pulling in more recent 0.8.x versions from npm.

**Comment by yardex** [comment]
You simply need to fixate your flot version to 0.8.x in package.json if I understand the problem correctly

**Comment by trickeyone** [comment]
Unfortunately, no. The only versions on the npm registry are 0.8.0-beta. We were using the github install method via `github:flot/flot#v0.8.3` but that stopped working as soon as the package was registered with the npm registry. Apparently, if a package name exists in the registry, it ignores attempting to install via github.

Fortunately, we tested upgrading to v2.1.6 and we're not seeing any major issues yet. But, we're only using a small bit of the functionality, so I can't speak to how much of a guarantee that is. It would still be a good idea to register the versions in the registry. All that a maintainer (or someone with npm access) would need to do is checkout the versions' tag and push the release to npm.

One tip I would give when publishing back-versions is to use the `npm dist-tags` functionality. To keep the most recent version at the 2.x, once the older versions have been registered, the `latest` tag would need to reset to the 2.1.6 version `npm dist-tags add flot@2.1.6 latest`. (I've had to do that for other packages I manage)

**Comment by jarekdobrzanski** [comment]
Agree, we definitely should have at least the 0.8.3 in the registry. There's lots of libraries downstream using flot

**Comment by mure** [comment]
Flot 0.8.3 has been published to npm.

**Comment by trickeyone** [comment]
Thanks for the quick response on this!
