### ISSUE TITLE
FAQ link down

### ISSUE THREAD

**Issue by mcandre** [flot/flot#1635]
The frequently asked questions on the homepage appears to be dead.

https://www.flotcharts.org/

**Comment by mure** [comment]
@atmgrifter00 do you think we should remove the link to the FAQ, or add it back to the repo? 
Here's what it used to be:
https://github.com/flot/flot/blob/958e5fd43c6dff4bab3e1fd5cb6109df5c1e8003/FAQ.md

**Comment by andig** [comment]
Same for the NEWS page. As I've just realized by pure luck that flot has come back to live (yeah!) it would be great to get a general update how things are and what the plan is regarding the codebase. We *love* fot and appreciate that it has been reborn!

**Comment by andrewdove1** [comment]
Fixed
