### ISSUE TITLE
Attribution issues

### ISSUE THREAD

**Issue by cipix2000** [flot/flot#1637]
In the process of merging ni-kismet/engineering-flot back into flot/flot the history of the engineering-flot didn't get properly merged and a lot of work that got done by multiple people in ni-kismet is missattributed in flot/flot. 

See the difference between:
https://github.com/ni-kismet/engineering-flot/graphs/contributors
https://github.com/flot/flot/graphs/contributors

**Comment by andrewdove1** [comment]
We had to move the code from engineering-flot to flot - but we kept engineering-flot around for history
