### ISSUE TITLE
Pie chart plothover fires extra events with null item

### ISSUE THREAD

**Issue by aalpern** [flot/flot#1645]
The behavior of the `plothover` event on pie charts has changed drastically between 0.8.3 and the current release.  The difference in behavior is easily observable in the `examples/series-pie/index.html` file, with the "Interactivity" demo, by adding a `console.log(event, pos, obj)` line to the `plothover` handler. 

### Behavior in 0.8.3

* One plothover event fires per mouse movement event
* A final event with a `null` value of `obj` is fired when the mouse exits the pie portion of the chart

That makes it very easy to, say, hide a tooltip when exiting the pie. 

### Behavior on master

* Every mouse movement triggers two plothover events - one with `obj` bound properly, and one with it set to `null`

The `flot-overlay` element is getting two `mousemove` handlers set - one from `jquery.flot.pie.js`, and one from `jquery.flot.hover.js`, which is included in the standard distribution. 

![image](https://user-images.githubusercontent.com/784846/56840115-a65cc400-683a-11e9-989e-8b753cf7a443.png)

This change breaks tooltips for pie charts.

**Comment by andrewdove1** [comment]
Fixed PR#1656

**Comment by aalpern** [comment]
Awesome, thank you!
