### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by cungar2000** [flot/flot#1654]
I'm getting a syntax error in Internet Explorer 11 pointing to the lines

eventList.sort((a, b) **=>** b.priority - a.priority );
            eventList.forEach( eventData **=>** {
                eventData.eventHolder.unbind(eventData.event, eventData.handler);
                eventData.eventHolder.bind(eventData.event, eventData.handler);

It's a know issue that IE11 doesn't support the => syntax. Does flot no longer support IE or am I the only one getting this?

**Comment by mure** [comment]
If you install flot through [NPM](https://www.npmjs.com/package/flot), there is a minified distribution for ES5, which IE 11 supports.

**Comment by cungar2000** [comment]
Thanks a lot. That worked. Had to tinker a bit with my code to make it IE11 compliant but it's working now. 

Still throwing a Object doesn't support this action for this line

var e=new CustomEvent("onDrawingDone");t.getEventHolder().dispatchEvent(e),t.getPlaceholder().trigger("drawingdone")}}

But the plots are working. I assume IE doesn't support custom events.

**Comment by andrewdove1** [comment]
You can find a polyfill for CustomEvent for IE [here](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent#Polyfill)

**Comment by amerina** [comment]
how can i find the special version for ie11? i find the same question here

**Comment by amerina** [comment]
get from: https://registry.npm.taobao.org/flot/download/flot-4.2.1.tgz
you can change the version for yourself
