### ISSUE TITLE
Hover actions ignored on all graphs except last one

### ISSUE THREAD

**Issue by ondrejj** [flot/flot#1676]
Looks like commit f05f817c149f4fd58bce3149943075f99e55afb7 named:
  Refactor hover so events get registered in the proper order

breaks some functionality. Without this commit I can use hover function on multiple graphs. With this commit it's not relevant, on which placeholder I call .bind("plothover"), it's always functional on latest graph only and ignored on all other graphs.

**Comment by jordaneliastam** [comment]
struggling with this as well.

**Comment by ondrejj** [comment]
Looks like version 3.2.7 fixed this. Closing. Reopen, if still persist.
