### ISSUE TITLE
legend options in API doc but not supported

### ISSUE THREAD

**Issue by jondbennett** [flot/flot#1678]
In the API documentation section "Customizing the Legend"
the code example reads as:

> container: null or jQuery object/DOM element/jQuery expression

> The placeholder is a jQuery object or DOM element or jQuery expression that the plot will be put into.

But a later paragraph reads:

> If you want the legend to appear somewhere else in the DOM, you can specify "container" as a jQuery object/expression to put the legend table into. The "position" and "margin" etc. options will then be ignored. Note that Flot will overwrite the contents of the container.

Note that the "DOM element" is missing from the type description.

Should the code support a DOM element name, or should the code example be changed to reflect the code?

**Comment by andrewdove1** [comment]
The container parameter is passed directly into the jquery selector $(). So the top statement is correct. The later statement is a little less precise. See jquery .flot.legend.js line 110
