### ISSUE TITLE
Right y-axis label not following axis during resize

### ISSUE THREAD

**Issue by jondbennett** [flot/flot#1679]
At least when using Firefox, ...

When using a separate y-axis on the right side of the graph, the axis label does not move during resizing. After rendering the graph, if you change the width of the window the axis label remains in place - either drifting into the graph or disappearing.

I've attached a stand-alone html file (renamed as a txt file) that reproduces the problem.

[jon_flot2.txt](https://github.com/flot/flot/files/3427228/jon_flot2.txt)

**Comment by andrewdove1** [comment]
Fixed https://github.com/flot/flot/pull/1685
