### ISSUE TITLE
[FIX] Labels not displaying for time axis type

### ISSUE THREAD

**Issue by trickeyone** [flot/flot#1792]
Version: 3.0.2

After reading and having the issue where axis tick marks weren't displaying for time axis type, I did some digging and discovered the issue was the attempt to override core functionality for the Date object. I've seen comments saying that the current version is still exhibiting this issue, as well.

The core issue appears to come down to overriding the core Date.prototype.getTime method. Since much of the code uses helper methods to update the various date-components (i.e. year, month, date, hour, minute, second, etc.) and not just calling `setTime`, the overridden-method `getTime` is set to only return the internally stored `microEpoch` value which would never be updated when calling these helper methods. Therefore, the `microEpoch` stored value is never updated, so when the `dateTickGenerator` function runs, it ends because the of `microEpoch` is never updated.

I tried to just override the `$.plot.dateGenerator` function, but since the plugin's init function always refers to the internal functions instead of referencing the `$.plot` functions, I had to override both `$.plot.dateGenerator` and `$.plot.dateTickGenerator`.

![Screen Shot 2021-08-12 at 2 06 14 PM](https://user-images.githubusercontent.com/1680555/129254324-5dcaab0c-bec6-4926-ba03-1c190d002d1d.png)

Anyway, here is the fix that I've implemented: https://gist.github.com/trickeyone/6d6394b73435b5a5a39f00c6bcfb03d6

**Comment by 7PH** [comment]
Hi @trickeyone , please check https://github.com/flot/flot/pull/1802 which fixes the issue directly in flot time's plugin
It would be very useful if you could check that it indeed fixes your issue as well

**Comment by trickeyone** [comment]
Hi @7PH . Unfortunately, I cannot test this in our setup as the decision was made to move away from jQuery, along with this plugin, in favor of converting to Angular and using a different charting library.

**Comment by 7PH** [comment]
Nice @trickeyone it's nice you found a solution

Out of curiosity, do you mind sharing the name of the library you moved to?

**Comment by trickeyone** [comment]
@7PH swimlane/ngx-charts

**Comment by 7PH** [comment]
Hello @trickeyone , could you please close this issue? A fix was merged for this issue (and this open issue is appearing in [our mention list](https://github.com/issues/mentioned) 😀)

**Comment by 7PH** [comment]
Hello, gentle reminder to close this issue as this is is fixed already 😁 @trickeyone @atmgrifter00

**Comment by trickeyone** [comment]
Closing per @7PH
