### ISSUE TITLE
Stacking visible for series amount of 0

### ISSUE THREAD

**Issue by dnschnur** [flot/flot#433]
_Original author: Edward.S...@gmail.com (May 20, 2010 11:20:50)_

Hello,

I have a stacked bar chart where some of the series have values of zero but
they are still visible on the chart.

On the attached screenshot - the first bar has a &quot;Disabled&quot; value of 291
and all other series have values of zero. On the second bar, &quot;Not Sent&quot; has
a value of 171 and all other series have values of zero. 

The bug is that a thin line of colour is clearly visable at the top and
bottom of the bars, which should not be visible because the values of the
other series is zero.

_Original issue: http://code.google.com/p/flot/issues/detail?id=354_

**Comment by slominskir** [comment]
This is still a bug - the only way to avoid having a line overlapping the bottom border of the chart area is to disable borders on bars.   This isn't great as borders are often needed / wanted on bars.
