### ISSUE TITLE
Touch support for selection plugin

### ISSUE THREAD

**Issue by dnschnur** [flot/flot#505]
_Original author: james.b...@gmail.com (October 11, 2010 00:21:15)_

Add touch support to the selection plugin (specifically for iPad support).

Patch attached allows you to select an area on a plot on an iPad using your finger in a similar manner to the way selection is currently done with the mouse.  This has been tested on Mobile Safari on iPad 3.2 and iPhone 4.0.  This works great for single finger touch and drag, however I'm not sure how to handle multiple touches appropriately.

_Original issue: http://code.google.com/p/flot/issues/detail?id=426_

**Comment by jinithjoseph** [comment]
How do I use the patch on a javascript file ? will it be picked up automatically ? Will I need to include it in the html 5 for being picked up ?

**Comment by chaveiro** [comment]
See https://github.com/flot/flot/pull/1431
