### ISSUE TITLE
Unexpected behavior when data is an empty array

### ISSUE THREAD

**Issue by dnschnur** [flot/flot#550]
_Original author: dragos.tihauan (February 24, 2011 20:56:16)_

When the graph is created with an empty array for the &quot;data&quot;, the axes are not created according to the options object and previous calls to setData and draw will result in an uncaught exception.

_Original issue: http://code.google.com/p/flot/issues/detail?id=471_

**Comment by awaism551** [comment]
xaxis: {
                    mode: "time",
                    timeformat: "%H:%M",
                    show: true
                },
                yaxis: {
                    max: max,
                    min: min,
                    show: true
                }
show: true worked for me as well thanks
