### ISSUE TITLE
Tooltip BUG + solve

### ISSUE THREAD

**Issue by dnschnur** [flot/flot#686]
_Original author: zniki...@gmail.com (September 27, 2011 14:22:34)_

Hello.
I have problem, when 2 graphs very closely and you focus on point with same dataIndex the tooltip not change!
This is my solution to fix it!

function addToolTips() {
 var previousPoint = null;
 $(&quot;#placeholder&quot;).bind(&quot;plothover&quot;, function (event, pos, item) {
  $(&quot;#x&quot;).text(pos.x.toFixed(2));
  $(&quot;#y&quot;).text(pos.y.toFixed(2));
  if (item) {
   if (previousPoint != item.dataIndex+item.series.label) {
    previousPoint = item.dataIndex+item.series.label;
    $(&quot;#tooltip&quot;).remove();
    var x = makeDateForToolTip(item.datapoint[0].toFixed(2)),
    y = Math.floor( item.datapoint[1].toFixed(2) ),
    str = &quot;&lt;b&gt;&quot; + item.series.label + &quot;&lt;/b&gt; [&quot; + y + &quot;]&lt;br&gt;&quot; + x;
    showTooltip(item.pageX, item.pageY,str);
   }
  } else {
   $(&quot;#tooltip&quot;).remove();
   previousPoint = null;
  }
 });
}

_Original issue: http://code.google.com/p/flot/issues/detail?id=607_

**Comment by arnaldinhobjj** [comment]
You can always set stack to null.
`series: {
                  stack: null,
              },`
