### ISSUE TITLE
Start adding tests using Qunit

### ISSUE THREAD

**Issue by brianpeiris** [flot/flot#965]
I'm creating this issue to discuss how we should start testing Flot. Aside from JSHint, we should start adding QUnit tests similar to how [jQuery](https://github.com/jquery/jquery/tree/master/test/unit) and [jQuery UI](https://github.com/jquery/jquery-ui/tree/master/tests/unit) do things. 

Note: One difference is that the jQuery group uses their own TestSwarm to run tests whereas we are now using Travis (similar to [how bootstrap does things](https://github.com/twitter/bootstrap/tree/master/js/tests)).

Regardless of how we run the tests, I'd like some input on how we should start covering the library. I see two ways of going about it:
- Start at the API and cover all of Flot's functionality bit by bit.
  - This would result in mostly-passing tests but would cover more of the code.
  - We would be able to write simple, straight-forward, unit tests around the core of Flot.
- Start with the bugs and create tests that reproduce them.
  - This would result in failing tests but would allow us to fix the existing bugs TDD style.
  - We might have to write complex tests to reproduce the bug.*
  - Perhaps we should triage the open issues first, so that we write tests starting with the most urgent bugs.

Your input is welcome.

\* Complex tests may require more than QUnit. We might have to use event simulation libraries like [Syn](http://funcunit.com/syn.html) or jQuery's own [simulate plugin](https://github.com/jquery/jquery-simulate) to simulate mouse events and mocking libraries like [Sinon](http://sinonjs.org/) to spy on calls to the Canvas API. Furthermore, since Flot is a very visual library, I would like to experiment with automated visual tests that use target images and image comparison to verify that Flot renders things correctly. However, these types of tests may be fragile in nature and, if they must be used, they should probably be restricted to the simplest test cases and regressions.

**Comment by Beakerboy** [comment]
Newest version now has unit testing and code coverage metrics.
